name: homelab

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.11.1
    command:
      - "--path.rootfs=/host"
      - "--web.listen-address=:${NODE_EXPORTER_PORT:-9100}"
    network_mode: host
    pid: host
    restart: unless-stopped
    read_only: true
    volumes:
      - "/:/host:ro,rslave"
