apiVersion: 1

datasources:
  - name: Wearable Infinity
    uid: wearable_infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      allowedHosts:
        - http://wearable-grafana-views:8000
